"""add status to checklist items

Revision ID: 1511c4176f46
Revises: 9cb37dab9143
Create Date: 2026-01-25 15:03:14.650360+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1511c4176f46'
down_revision = '9cb37dab9143'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_checklist_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
