"""Enhance checklist system with named groups and descriptions

Revision ID: 7508abb323d3
Revises: e65a56a523ac
Create Date: 2026-01-25 11:14:10.280723+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7508abb323d3'
down_revision = 'e65a56a523ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_issue_id'), ['issue_id'], unique=False)

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('issue_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_checklist_items_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_foreign_key('fk_checklist_items_checklist_id', 'checklists', ['checklist_id'], ['id'])

    # Data Migration: Create default checklists for existing items
    import uuid
    from datetime import datetime
    
    connection = op.get_bind()
    
    # Get all unique issue_ids that have checklist items
    items = connection.execute(sa.text("SELECT DISTINCT issue_id FROM checklist_items WHERE issue_id IS NOT NULL")).fetchall()
    
    for row in items:
        issue_id = row[0]
        checklist_id = str(uuid.uuid4())
        now = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
        
        # Create a default checklist for this issue
        connection.execute(sa.text(
            "INSERT INTO checklists (id, issue_id, name, position, created_at, updated_at) "
            "VALUES (:id, :issue_id, 'Checklist', 0, :now, :now)"
        ).bindparams(id=checklist_id, issue_id=issue_id, now=now))
        
        # Point existing items to this checklist
        connection.execute(sa.text(
            "UPDATE checklist_items SET checklist_id = :checklist_id WHERE issue_id = :issue_id"
        ).bindparams(checklist_id=checklist_id, issue_id=issue_id))

    # Final Schema Cleanup: Make checklist_id non-nullable and drop issue_id
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        # Drop the old foreign key constraint first
        if connection.engine.dialect.name == "mysql":
            batch_op.drop_constraint('checklist_items_ibfk_1', type_='foreignkey')
        else:
            # Fallback for other dialects if needed, or if naming is automatic
            batch_op.drop_constraint(None, type_='foreignkey')

        batch_op.alter_column('checklist_id',
               existing_type=sa.String(length=36),
               nullable=False)
        batch_op.drop_column('issue_id')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint('fk_checklist_items_checklist_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checklist_items_checklist_id'))
        batch_op.alter_column('issue_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('checklist_id')

    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_issue_id'))

    op.drop_table('checklists')
    # ### end Alembic commands ###

