"""add project pins

Revision ID: 9cb37dab9143
Revises: e53528f63bd7
Create Date: 2026-01-25 12:03:23.099183+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb37dab9143'
down_revision = 'e53528f63bd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_pins',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_pins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_pins_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_pins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_pins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_pins_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_pins_project_id'))

    op.drop_table('project_pins')
    # ### end Alembic commands ###
