"""Initial schema with all core models

Revision ID: 278190315932
Revises: 
Create Date: 2026-01-24 15:15:37.856467+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278190315932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_organization_id'), ['organization_id'], unique=False)

    op.create_table('teams',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('team_type', sa.String(length=50), nullable=True),
    sa.Column('parent_team_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('activities',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('issue', 'feature', 'project', 'comment', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_organization_id'), ['organization_id'], unique=False)

    op.create_table('projects',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('lead_user_id', sa.String(length=36), nullable=True),
    sa.Column('default_assignee_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_issue_number', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('team_members',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('lead', 'member', name='teamrole'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('components',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('lead_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_project_id'), ['project_id'], unique=False)

    op.create_table('labels',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='projectrole'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('features',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('feature_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('component_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'planning', 'in_progress', 'testing', 'completed', 'cancelled', name='featurestatus'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('target_release', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_status'), ['status'], unique=False)

    op.create_table('issues',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('issue_key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.Enum('bug', 'task', 'sub_task', 'story', 'improvement', name='issuetype'), nullable=False),
    sa.Column('repro_steps', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('error_signature', sa.String(length=500), nullable=True),
    sa.Column('is_regression', sa.Boolean(), nullable=False),
    sa.Column('affected_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'review', 'done', 'closed', 'wont_fix', name='issuestatus'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('severity', sa.Enum('blocker', 'critical', 'major', 'minor', 'trivial', name='severity'), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('component_id', sa.String(length=36), nullable=True),
    sa.Column('parent_issue_id', sa.String(length=36), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('time_estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('deduplication_hash', sa.String(length=64), nullable=True),
    sa.Column('similarity_vector', sa.Text(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_deduplication_hash'), ['deduplication_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_issue_key'), ['issue_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_issues_issue_type'), ['issue_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('issue_id', sa.String(length=36), nullable=True),
    sa.Column('feature_id', sa.String(length=36), nullable=True),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_issue_id'), ['issue_id'], unique=False)

    op.create_table('feature_issue_links',
    sa.Column('feature_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('link_type', sa.Enum('implements', 'blocks', 'relates_to', 'caused_by', name='featureissuelinktype'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_issue_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_issue_links_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_issue_links_issue_id'), ['issue_id'], unique=False)

    op.create_table('issue_labels',
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('label_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'label_id')
    )
    op.create_table('issue_links',
    sa.Column('source_issue_id', sa.String(length=36), nullable=False),
    sa.Column('target_issue_id', sa.String(length=36), nullable=False),
    sa.Column('link_type', sa.Enum('blocks', 'is_blocked_by', 'relates_to', 'duplicates', 'is_duplicated_by', 'clones', 'is_cloned_from', name='issuelinktype'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_links_source_issue_id'), ['source_issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_links_target_issue_id'), ['target_issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_links_target_issue_id'))
        batch_op.drop_index(batch_op.f('ix_issue_links_source_issue_id'))

    op.drop_table('issue_links')
    op.drop_table('issue_labels')
    with op.batch_alter_table('feature_issue_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_issue_links_issue_id'))
        batch_op.drop_index(batch_op.f('ix_feature_issue_links_feature_id'))

    op.drop_table('feature_issue_links')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_issue_id'))
        batch_op.drop_index(batch_op.f('ix_comments_feature_id'))

    op.drop_table('comments')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_issues_project_id'))
        batch_op.drop_index(batch_op.f('ix_issues_organization_id'))
        batch_op.drop_index(batch_op.f('ix_issues_issue_type'))
        batch_op.drop_index(batch_op.f('ix_issues_issue_key'))
        batch_op.drop_index(batch_op.f('ix_issues_deduplication_hash'))
        batch_op.drop_index(batch_op.f('ix_issues_assignee_id'))

    op.drop_table('issues')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_status'))
        batch_op.drop_index(batch_op.f('ix_features_project_id'))
        batch_op.drop_index(batch_op.f('ix_features_organization_id'))

    op.drop_table('features')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_project_id'))

    op.drop_table('labels')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_project_id'))

    op.drop_table('components')
    op.drop_table('user_roles')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    op.drop_table('role_permissions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_activities_entity_id'))

    op.drop_table('activities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_organization_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
