"""Add assignee to checklist items

Revision ID: e53528f63bd7
Revises: 7508abb323d3
Create Date: 2026-01-25 11:36:48.180003+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53528f63bd7'
down_revision = '7508abb323d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_checklist_items_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['assignee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checklist_items_assignee_id'))
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###
