"""Add checklist items

Revision ID: e65a56a523ac
Revises: 657f03fc1c65
Create Date: 2026-01-25 09:45:05.006519+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e65a56a523ac'
down_revision = '657f03fc1c65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_items',
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_issue_id'), ['issue_id'], unique=False)

    with op.batch_alter_table('comment_mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('digest_frequency',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'daily'"))

    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_index('ix_reminder_rules_last_executed_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_rules_last_executed_at', ['last_executed_at'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.alter_column('digest_frequency',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'daily'"))

    with op.batch_alter_table('comment_mentions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_issue_id'))

    op.drop_table('checklist_items')
    # ### end Alembic commands ###
